name: Deploy Zola to Azure SWA (OIDC)

on:
  push:
    branches: [main]
    paths-ignore:
      - 'infra/**'
      - '.github/workflows/infra.yml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_SWA_DEPLOYMENT_TOKEN: ${{ secrets.AZ_SWA_DEPLOYMENT_TOKEN }}
      AZURE_RESOURCE_GROUP:       rg-static-vibe
      AZURE_SWA_NAME:             swapp-vibe-ntv-ooga

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Set up Zola
      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola

      # Build Zola site
      - name: Build site
        working-directory: site
        run: zola build

      # Install Node.js for image optimization & resizing
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install Sharp CLI & imagemin
      - name: Install image tools
        run: npm install -g sharp-cli imagemin-cli imagemin-mozjpeg imagemin-pngquant imagemin-svgo imagemin-gifsicle imagemin-webp

      # Resize large images (>1200px width) & convert to WebP
      - name: Resize & Convert to WebP
        working-directory: site/public
        run: |
          find . \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \) -type f | while read -r img; do
            sharp "$img" --resize 1200 --format webp --output "${img%.*}.webp"
          done

      # Optimize original images (fallback formats)
      - name: Optimize fallback images
        working-directory: site/public
        run: |
          imagemin "**/*.{jpg,jpeg,png,gif,svg}" \
            --plugin=mozjpeg \
            --plugin=pngquant \
            --plugin=svgo \
            --plugin=gifsicle \
            --out-dir=.

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_SWA_DEPLOYMENT_TOKEN }}
          action: "upload"
          app_location: "site/public"
          skip_app_build: true
          swa_name: ${{ env.AZURE_SWA_NAME }}
          resource_group: ${{ env.AZURE_RESOURCE_GROUP }}
