name: Deploy Zola to Azure SWA (OIDC)

on:
  push:
    branches: [main]
    paths-ignore:
      - 'infra/**'
      - '.github/workflows/infra.yml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_SWA_DEPLOYMENT_TOKEN: ${{ secrets.AZ_SWA_DEPLOYMENT_TOKEN }}
      AZURE_RESOURCE_GROUP:       rg-static-vibe
      AZURE_SWA_NAME:             swapp-vibe-ntv-ooga

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Set up Zola
      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola

      # Build Zola site
      - name: Build site
        working-directory: site
        run: zola build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_SWA_DEPLOYMENT_TOKEN }}
          action: "upload"
          app_location: "site/public"
          skip_app_build: true
          swa_name: ${{ env.AZURE_SWA_NAME }}
          resource_group: ${{ env.AZURE_RESOURCE_GROUP }}
