name: infra
on:
  push:
    paths: ['infra/**', '.github/workflows/infra.yml']
    branches: [main]

jobs:
  apply:
    permissions: { id-token: write, contents: read }
    runs-on: ubuntu-latest

    env:
      ARM_USE_OIDC:           "true"
      ARM_CLIENT_ID:          ${{ secrets.AZ_CLIENT_ID }}
      ARM_TENANT_ID:          ${{ secrets.AZ_TENANT_ID }}
      ARM_SUBSCRIPTION_ID:    ${{ secrets.AZ_SUB_ID }}
      TF_VAR_client_id:       ${{ secrets.AZ_CLIENT_ID }}
      TF_VAR_tenant_id:       ${{ secrets.AZ_TENANT_ID }}
      TF_VAR_subscription_id: ${{ secrets.AZ_SUB_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform -chdir=infra init

      - name: Terraform apply
        run: terraform -chdir=infra apply -auto-approve -input=false
